name: Executar Script Bash e Enviar para S3

on:
  workflow_dispatch:
  # schedule: # tipo da trigger 
    # - cron: "16 17 * * 5" # Toda sexta-feira às 12h UTC

jobs:
  run-bash-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      
      - uses: actions/upload-artifact@v4
        with:
          name: strigus-upload
          path: ${{ github.workspace }}/script.sh

      - name: Tornar script executável
        run: chmod +x script.sh

      - name: Executar script
        run: ${{ github.workspace }}/script.sh

      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # ajusta para a tua região

      - name: Enviar arquivo para S3
        run: |
          aws s3 cp resultado.txt s3://aula-terraform-tamiris/desafio-teamcard/resultado-$(date +%Y-%m-%d).txt
