name: workflow do desafio  1

on:
  workflow_dispatch:
    inputs:
        informaraImage:
            required: true
            type: string
            default: 'nginx:latest'
            description: 'Necessário informar a image para o pull'


jobs:
  baixandoaimage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout - ação para baixar o conteudo do repositório
        uses: actions/checkout@v4
      
      - name: Login no Docker
        uses:  docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: verificando versão do docker
        run: |
          docker version

      - name: Baixa a imagem do Container
        run: |
          docker pull ${{ github.event.inputs.informaraImage }}