name: Executando script

on:  
  workflow_dispatch:
  # schedule:
  #   - cron: "0 12 * * 5" # Toda sexta-feira às 12h UTC

jobs:
  job-executor-scripts:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./scripts  # define o diretório de trabalho padrão para os steps desse jop
    steps:
      - name: Checkout do Repo
        uses: actions/checkout@v4
      - name: Transformando o nosso script em executaveis  
        run: chmod +x script.sh

      - name: Executando
        run: | #os scripts serão executados a partir de './scripts'
           ./script.sh
      
      - name: listar os arquivos no workspace
        run: ls -lha 
    
      - name: Upload do arquivo gerado
        uses: actions/upload-artifact@v4
        with:
          name: bash-upload
          path: scripts/resultado.txt  
 
  
  job-download:
    runs-on: ubuntu-latest
    needs: job-executor-scripts
    steps:
      - name: Ver conteúdo inicial do diretório
        run: ls -lha

      - name: Download do arquivo
        uses: actions/download-artifact@v4
        with:
          name: bash-upload          # nome igual ao do upload
          path: bash-upload

      - name: Listar arquivos após download
        run: ls -lha ./bash-upload/resultado.txt

      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Enviar arquivo para S3
        run: |
          aws s3 cp bash-upload/resultado.txt s3://aula-terraform-tamiris/desafio-teamcard/resultado-$(date +%Y-%m-%d).txt
