name: Testando o trigger do tipo create

on:
  create 
  
jobs:
  print-branch-or-tag-creation:
    runs-on: ubuntu-latest
    steps:

      - name: Avisa sobre criação da brannch ou tag
        run: echo "Uma nova branch ou tag foi criada"