name: Criando nosso trigger issue

on:
  issues:
    types: [opened, edited, deleted]

jobs:
  job-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Printa issue
        run: echo "Uma issue foi aberta, editada e deletada"